/**
 * Declarative UDT/UDF/UDO schema for the Job Work module, transcribed 1:1 from the
 * legacy SAP B1 UI-API add-on at JobWork\Database\UDClass.cs (only the active,
 * non-commented-out CreateTable/CreateColumn/CreateObject calls).
 *
 * Field `type` values map to SAP's BoFieldTypes: 'Alpha' | 'Numeric' | 'Date' | 'Float' | 'Memo'.
 * `validValues` mirrors the named picklists used in UDClass.cs's CreateColumn(ValidValues=...).
 *
 * This file is pure data — no SAP/network calls — so it can be diffed against
 * UDClass.cs directly to check for parity.
 */

const VALID_VALUES = {
  NY: { values: [{ value: 'Y', description: 'Yes' }, { value: 'N', description: 'No' }] },
  JWStatus: {
    values: [
      { value: 'O', description: 'Open' },
      { value: 'C', description: 'Closed' },
      { value: 'CA', description: 'Cancelled' },
    ],
    defaultValue: 'O',
  },
  JERSTS: {
    values: [
      { value: 'O', description: 'Open' },
      { value: 'C', description: 'Closed' },
      { value: 'CA', description: 'Cancelled' },
    ],
    defaultValue: 'O',
  },
  RFPType: {
    values: [{ value: 'REC', description: 'Receipt' }, { value: 'RET', description: 'Return' }],
    defaultValue: 'REC',
  },
  JWRTNTYP: {
    values: [
      { value: 'RP', description: 'Re-Process' },
      { value: 'AR', description: 'A/R Credit Note' },
      { value: 'AP', description: 'A/P Invoice' },
      { value: 'SC', description: 'Short Close' },
    ],
    defaultValue: 'SC',
  },
};

// Bill-to (STTL_JWSM: "B..." fields) address block, shared shape reused inline below.
const billToAddressFields = () => [
  { name: 'BillTo', description: 'Bill To', type: 'Alpha', size: 50 },
  { name: 'BAdresID', description: 'Address ID', type: 'Alpha', size: 50 },
  { name: 'BStreet', description: 'Street', type: 'Alpha', size: 100 },
  { name: 'BStretNo', description: 'Street No', type: 'Alpha', size: 100 },
  { name: 'BBuildg', description: 'Building', type: 'Memo', size: 100 },
  { name: 'BBlock', description: 'Block No', type: 'Alpha', size: 100 },
  { name: 'BCity', description: 'City', type: 'Alpha', size: 100 },
  { name: 'BZCode', description: 'Zip Code', type: 'Alpha', size: 20 },
  { name: 'BCounty', description: 'County', type: 'Alpha', size: 100 },
  { name: 'BContry', description: 'Country', type: 'Alpha', size: 100 },
  { name: 'BState', description: 'State', type: 'Alpha', size: 100 },
  { name: 'BGSTIN', description: 'GSTIN', type: 'Alpha', size: 15 },
  { name: 'BGSTType', description: 'GSTType', type: 'Alpha', size: 15 },
];

// Ship-from (STTL_JWSM: "S..." fields) address block.
const shipFromAddressFields = () => [
  { name: 'ShipTo', description: 'Ship From', type: 'Alpha', size: 50 },
  { name: 'SAdresID', description: 'Address ID', type: 'Alpha', size: 50 },
  { name: 'SStreet', description: 'Street', type: 'Alpha', size: 100 },
  { name: 'SStretNo', description: 'Street No', type: 'Alpha', size: 100 },
  { name: 'SBuildg', description: 'Building', type: 'Memo', size: 100 },
  { name: 'SBlock', description: 'Block No', type: 'Alpha', size: 100 },
  { name: 'SCity', description: 'City', type: 'Alpha', size: 100 },
  { name: 'SZCode', description: 'Zip Code', type: 'Alpha', size: 20 },
  { name: 'SCounty', description: 'County', type: 'Alpha', size: 100 },
  { name: 'SContry', description: 'Country', type: 'Alpha', size: 100 },
  { name: 'SState', description: 'State', type: 'Alpha', size: 100 },
  { name: 'SGSTIN', description: 'GSTIN', type: 'Alpha', size: 15 },
  { name: 'SGSTType', description: 'GSTType', type: 'Alpha', size: 15 },
];

/**
 * The 4 sidebar transactions (Menu.cs: JW_Sales, JW_SalesR, JW_Pur, JW_PurR).
 * `udo.objectType` becomes both the Service Layer UDO resource path (e.g. POST /STTL_JWPM)
 * and the UserObjectsMD Code.
 */
const TRANSACTIONS = {
  customerReceiptNote: {
    menuName: 'Customer Receipt Note',
    menuPath: '/customer-receipt-note',
    group: 'Sales J/W',
    partyType: 'customer',
    listFields: { statusField: 'JWSts', partyCodeField: 'CCode', partyNameField: 'CName', postingDateField: 'PDate', docDateField: 'DocDate', primaryLineTable: 'STTL_JWS12' },
    masterTable: { name: 'STTL_JWSM', description: 'Jobwork Sales Master' },
    childTables: [
      { name: 'STTL_JWS1', description: 'Jobwork Sales Attach Detail', role: 'attachments' },
      { name: 'STTL_JWS12', description: 'Jobwork Sales RGR Detail', role: 'lines' },
    ],
    masterFields: [
      { name: 'JWNo', description: 'Jobwork Order No', type: 'Alpha', size: 50 },
      { name: 'JWSer', description: 'Jobwork Order Series', type: 'Alpha', size: 50 },
      { name: 'JWSts', description: 'Jobwork Order Status', type: 'Alpha', size: 50, validValues: 'JWStatus' },
      { name: 'JWBranch', description: 'Jobwork Branch', type: 'Alpha', size: 50 },
      { name: 'PDate', description: 'Posting Date', type: 'Date' },
      { name: 'DDate', description: 'Delivery Date', type: 'Date' },
      { name: 'DocDate', description: 'Document Date', type: 'Date' },
      { name: 'CCode', description: 'Customer Code', type: 'Alpha', size: 50 },
      { name: 'CName', description: 'Customer Name', type: 'Alpha', size: 150 },
      { name: 'TranName', description: 'Transporter Name', type: 'Alpha', size: 100 },
      { name: 'ChallanNo', description: 'Challan No', type: 'Alpha', size: 50 },
      { name: 'ChallanDt', description: 'Challan Date', type: 'Date' },
      { name: 'NatureP', description: 'Nature Of Process', type: 'Alpha', size: 50 },
      { name: 'GRSeries', description: 'Series G Receipt No', type: 'Alpha', size: 50 },
      { name: 'GRNo', description: 'Goods Receipt No', type: 'Alpha', size: 50 },
      { name: 'GINo', description: 'Goods issue', type: 'Alpha', size: 50 },
      { name: 'GISeries', description: 'Goods Issue Series', type: 'Alpha', size: 50 },
      { name: 'Canclled', description: 'Cancelled', type: 'Alpha', size: 50 },
      // Dedicated fields for the web app's own linked-document tracking
      // (mirrors jobworkIssueNote's WebInvTraDocEntry pair) — kept separate
      // from the legacy GRNo/GRSeries pair above, which are free-text fields
      // the legacy add-on filled in manually rather than a real SAP link.
      { name: 'WebGoodsRcptDocEntry', description: 'Web Goods Receipt DocEntry', type: 'Numeric' },
      { name: 'WebGoodsRcptDocNum', description: 'Web Goods Receipt DocNum', type: 'Numeric' },
      ...billToAddressFields(),
      ...shipFromAddressFields(),
      { name: 'VEHNO', description: 'Vehicle Number', type: 'Alpha', size: 50 },
      { name: 'KNTWEIGHT', description: 'Kata Weight', type: 'Alpha', size: 100 },
      { name: 'EWBILLNO', description: 'EWAYBILLNO', type: 'Alpha', size: 50 },
      { name: 'FrmLocC', description: 'From Location Country', type: 'Alpha', size: 50 },
      { name: 'FrmLocS', description: 'From Location State', type: 'Alpha', size: 50 },
      { name: 'ToLocC', description: 'To Location Country', type: 'Alpha', size: 50 },
      { name: 'ToLocS', description: 'To Location State', type: 'Alpha', size: 50 },
      { name: 'Remarks', description: 'Remarks', type: 'Memo', size: 50 },
    ],
    childFields: {
      STTL_JWS1: [
        { name: 'Path', description: 'Target Path', type: 'Memo', size: 50 },
        { name: 'FName', description: 'File Name', type: 'Alpha', size: 254 },
        { name: 'ADate', description: 'Attachment Date', type: 'Date' },
        { name: 'FText', description: 'Free Text', type: 'Alpha', size: 100 },
      ],
      STTL_JWS12: [
        { name: 'GRNo', description: 'GRNo', type: 'Alpha', size: 50 },
        { name: 'ICode', description: 'ItemCode', type: 'Alpha', size: 50 },
        { name: 'IName', description: 'ItemName', type: 'Alpha', size: 150 },
        { name: 'Qty', description: 'Qty', type: 'Float' },
        { name: 'WhsCode', description: 'WhsCode', type: 'Alpha', size: 50 },
        { name: 'UOM', description: 'UOM', type: 'Alpha', size: 50 },
        { name: 'Batch', description: 'Batch', type: 'Alpha', size: 50 },
        { name: 'BinCode', description: 'BinCode', type: 'Alpha', size: 50 },
        { name: 'ErrMsg', description: 'Error Msg', type: 'Alpha', size: 250 },
        { name: 'Price', description: 'Price', type: 'Float' },
        { name: 'Series', description: 'Series', type: 'Alpha', size: 50 },
        { name: 'PcsMtr', description: 'PcsMtr', type: 'Float' },
        { name: 'GWeight', description: 'Gross Weight', type: 'Float' },
        { name: 'TWeight', description: 'Tare Weight', type: 'Float' },
        { name: 'PipeBob', description: 'pipe bobin', type: 'Alpha', size: 200 },
        { name: 'taxCode', description: 'tax Code', type: 'Alpha', size: 200 },
        { name: 'Remarks', description: 'Remarks', type: 'Alpha', size: 210 },
        { name: 'AccountCode', description: 'G/L Account', type: 'Alpha', size: 50 },
      ],
    },
    udo: {
      objectType: 'STTL_JWSM',
      name: 'Jobwork Sales Master',
      manageSeries: true,
      childTables: ['STTL_JWS1', 'STTL_JWS12'],
      findColumns: ['JWNo', 'JWSts', 'DDate', 'DocDate', 'CCode', 'CName'],
    },
  },

  customerIssueReturnNote: {
    menuName: 'Customer Issue / Return Note',
    menuPath: '/customer-issue-note',
    group: 'Sales J/W',
    partyType: 'customer',
    listFields: { statusField: 'JWSts', partyCodeField: 'CCode', partyNameField: 'CName', postingDateField: 'PDate', docDateField: 'DocDate', primaryLineTable: 'STTL_JWSR10' },
    masterTable: { name: 'STTL_JWSR', description: 'Jobwork Sales Return' },
    childTables: [
      { name: 'STTL_JWSR1', description: 'Jobwork Sales Attach Detail', role: 'attachments' },
      { name: 'STTL_JWSR10', description: 'Jobwork Sales DSO Detail', role: 'lines' },
      { name: 'STTL_JWSR12', description: 'Jobwork Sales RGR Detail', role: 'lines2' },
    ],
    masterFields: [
      { name: 'JWRtn', description: 'Jobwork Return Type', type: 'Alpha', size: 50, validValues: 'JWRTNTYP' },
      { name: 'JWNo', description: 'Jobwork Order No', type: 'Alpha', size: 50 },
      { name: 'JWSer', description: 'Jobwork Order Series', type: 'Alpha', size: 50 },
      { name: 'JWSts', description: 'Jobwork Order Status', type: 'Alpha', size: 50, validValues: 'JERSTS' },
      { name: 'JWBranch', description: 'Jobwork Branch', type: 'Alpha', size: 50 },
      { name: 'PDate', description: 'Posting Date', type: 'Date' },
      { name: 'DDate', description: 'Delivery Date', type: 'Date' },
      { name: 'DocDate', description: 'Document Date', type: 'Date' },
      { name: 'CCode', description: 'Customer Code', type: 'Alpha', size: 50 },
      { name: 'CName', description: 'Customer Name', type: 'Alpha', size: 150 },
      { name: 'PTerm', description: 'Payment Term', type: 'Alpha', size: 50 },
      { name: 'SEmp', description: 'Sales Employee', type: 'Alpha', size: 50 },
      { name: 'CPONo', description: 'Customer PO No', type: 'Alpha', size: 50 },
      { name: 'CPODT', description: 'Customer PO Date', type: 'Date' },
      { name: 'PONo', description: 'Production No', type: 'Alpha', size: 50 },
      { name: 'TranName', description: 'Transporter Name', type: 'Alpha', size: 100 },
      { name: 'ChallanNo', description: 'Challan No', type: 'Alpha', size: 50 },
      { name: 'ChallanDt', description: 'Challan Date', type: 'Date' },
      { name: 'NatureP', description: 'Nature Of Process', type: 'Alpha', size: 50 },
      { name: 'JWRType', description: 'Job work return type', type: 'Alpha', size: 50 },
      ...billToAddressFields(),
      ...shipFromAddressFields(),
      { name: 'FrmLocC', description: 'From Location Country', type: 'Alpha', size: 50 },
      { name: 'FrmLocS', description: 'From Location State', type: 'Alpha', size: 50 },
      { name: 'ToLocC', description: 'To Location Country', type: 'Alpha', size: 50 },
      { name: 'ToLocS', description: 'To Location State', type: 'Alpha', size: 50 },
      { name: 'InvTra', description: 'Inventory transfer Req.', type: 'Alpha', size: 50 },
      { name: 'CInvTra', description: 'Cancle Inv. Tra. req.', type: 'Alpha', size: 50 },
      { name: 'GoodsIssueN', description: 'Goods Iss No', type: 'Alpha', size: 50 },
      { name: 'CGoodsIssueN', description: 'Cancle goods Iss', type: 'Alpha', size: 100 },
      { name: 'GoodsReceiptNo', description: 'Goods Rec No', type: 'Alpha', size: 50 },
      { name: 'CGoodsReceiptNo', description: 'Cancle Goods Rec No', type: 'Alpha', size: 50 },
      { name: 'ISeries', description: 'Inv. Tra. Series', type: 'Alpha', size: 100 },
      { name: 'GRSeries', description: 'Goods Rec. Series', type: 'Alpha', size: 50 },
      { name: 'GISeries', description: 'Goods Iss. Series', type: 'Alpha', size: 50 },
      { name: 'GoodsReceiptN', description: 'Goods Rec. Series', type: 'Alpha', size: 50 },
      { name: 'JWTStat', description: 'Job work Satus', type: 'Alpha', size: 50 },
      { name: 'Remarks', description: 'Remarks', type: 'Memo', size: 50 },
      // Dedicated fields for the web app's own linked-document tracking
      // (mirrors customerReceiptNote's WebGoodsRcptDocEntry pair) — the real
      // SAP link, separate from the legacy GoodsIssueN/GISeries free-text pair
      // above, which the old add-on filled in manually rather than linking.
      { name: 'WebGoodsIssDocEntry', description: 'Web Goods Issue DocEntry', type: 'Numeric' },
      { name: 'WebGoodsIssDocNum', description: 'Web Goods Issue DocNum', type: 'Numeric' },
    ],
    childFields: {
      STTL_JWSR1: [
        { name: 'Path', description: 'Target Path', type: 'Memo', size: 50 },
        { name: 'FName', description: 'File Name', type: 'Alpha', size: 254 },
        { name: 'ADate', description: 'Attachment Date', type: 'Date' },
        { name: 'FText', description: 'Free Text', type: 'Alpha', size: 100 },
      ],
      STTL_JWSR10: [
        { name: 'GINo', description: 'GINo', type: 'Alpha', size: 50 },
        { name: 'ICode', description: 'ItemCode', type: 'Alpha', size: 50 },
        { name: 'IName', description: 'ItemName', type: 'Alpha', size: 150 },
        { name: 'Qty', description: 'Qty', type: 'Float' },
        { name: 'WhsCode', description: 'WhsCode', type: 'Alpha', size: 50 },
        { name: 'UOM', description: 'UOM', type: 'Alpha', size: 50 },
        { name: 'Batch', description: 'Batch', type: 'Alpha', size: 50 },
        { name: 'BinCode', description: 'BinCode', type: 'Alpha', size: 50 },
        { name: 'Series', description: 'Series', type: 'Alpha', size: 50 },
        { name: 'ErrMsg', description: 'Error Msg', type: 'Alpha', size: 250 },
        { name: 'OPCode', description: 'Opration Code', type: 'Alpha', size: 100 },
        { name: 'INStockQty', description: 'In Stock Qty', type: 'Float' },
        { name: 'QTYInWhs', description: 'Quantity in whse', type: 'Float' },
        { name: 'Rate', description: 'Rate', type: 'Float' },
        { name: 'PcsMtr', description: 'Pcs / Mtr', type: 'Float' },
        { name: 'GWeight', description: 'Gross Weight', type: 'Float' },
        { name: 'TWeight', description: 'Tare Weight', type: 'Float' },
        { name: 'PBobin', description: 'Pipe Bobin', type: 'Alpha', size: 100 },
        { name: 'TaxCode', description: 'TaxCode', type: 'Alpha', size: 100 },
        { name: 'Remarks', description: 'Remarks', type: 'Alpha', size: 250 },
      ],
      STTL_JWSR12: [
        { name: 'CRecKey', description: 'Customer Rec key', type: 'Alpha', size: 50 },
        { name: 'CRecNo', description: 'Customer Rec No.', type: 'Alpha', size: 50 },
        { name: 'RecNo', description: 'RecNo', type: 'Alpha', size: 50 },
        { name: 'AnnxNo', description: 'Annecture number', type: 'Alpha', size: 100 },
        { name: 'ItemCode', description: 'Item Code', type: 'Alpha', size: 100 },
        { name: 'ItemDesc', description: 'Item Desc', type: 'Alpha', size: 100 },
        { name: 'Qty', description: 'Quantity', type: 'Float' },
        { name: 'WhsCode', description: 'WhsCode', type: 'Alpha', size: 100 },
        { name: 'BinCode', description: 'BinCode', type: 'Alpha', size: 100 },
        { name: 'Remarks', description: 'Batch', type: 'Alpha', size: 200 },
        { name: 'IssueQty', description: 'Issue Quantity', type: 'Float' },
        { name: 'BALQTY', description: 'Balance Quantity', type: 'Float' },
        { name: 'FBAL', description: 'Final Quantity', type: 'Float' },
      ],
    },
    udo: {
      objectType: 'STTL_JWSR',
      name: 'Jobwork Sales Return',
      manageSeries: true,
      childTables: ['STTL_JWSR1', 'STTL_JWSR10', 'STTL_JWSR12'],
      findColumns: ['JWNo', 'JWSts', 'DDate', 'DocDate', 'CCode', 'CName', 'SEmp', 'CPONo', 'CPODT'],
    },
  },

  jobworkIssueNote: {
    menuName: 'Jobwork Issue Note',
    menuPath: '/jobwork-issue-note',
    group: 'Purchase J/W',
    partyType: 'vendor',
    listFields: { statusField: 'JWOSTS', partyCodeField: 'VENCOD', partyNameField: 'VENNAME', postingDateField: 'PDATE', docDateField: 'DOCDATE', primaryLineTable: 'STTL_JWP6' },
    masterTable: { name: 'STTL_JWPM', description: 'JobWork Purchase Master' },
    childTables: [
      { name: 'STTL_JWP1', description: 'JobWork P Attachment Detail', role: 'attachments' },
      { name: 'STTL_JWP2', description: 'JobWork P PO Detail', role: 'related' },
      { name: 'STTL_JWP3', description: 'JobWork P AP Detail', role: 'related' },
      { name: 'STTL_JWP4', description: 'JobWork P IFP Detail', role: 'related' },
      { name: 'STTL_JWP5', description: 'JobWork P RFP Detail', role: 'related' },
      { name: 'STTL_JWP6', description: 'JobWork P DELIFP Detail', role: 'lines' },
      { name: 'STTL_JWP7', description: 'JobWork P DELPO Detail', role: 'lines2' },
      { name: 'STTL_JWP8', description: 'JobWork P Goods Issue Detail', role: 'goodsIssue' },
      { name: 'STTL_JWP9', description: 'JobWork P GoodsReceipt Detail', role: 'goodsReceipt' },
    ],
    masterFields: [
      { name: 'JWOSER', description: 'Jobwork Order Series', type: 'Alpha', size: 50 },
      { name: 'JWONUO', description: 'Jobwork Order No', type: 'Alpha', size: 50 },
      { name: 'JWOSTS', description: 'Jobwork Order Status', type: 'Alpha', size: 50 },
      { name: 'BRNCH', description: 'Branch', type: 'Alpha', size: 50 },
      { name: 'PDATE', description: 'Posting Date', type: 'Date' },
      { name: 'DDATE', description: 'Delivery Date', type: 'Date' },
      { name: 'DOCDATE', description: 'Document Date', type: 'Date' },
      { name: 'OWOR', description: 'Own Work Order Ref', type: 'Alpha', size: 50 },
      { name: 'VENCOD', description: 'Vendor Code', type: 'Alpha', size: 50 },
      { name: 'VENNAME', description: 'Vendor Name', type: 'Alpha', size: 100 },
      { name: 'JWOPAYT', description: 'Payment Term', type: 'Alpha', size: 50 },
      { name: 'SLSEMP', description: 'Sales Employee', type: 'Alpha', size: 50 },
      { name: 'VEHNO', description: 'Vehicle Number', type: 'Alpha', size: 50 },
      { name: 'KNTWEIGHT', description: 'Kata Weight', type: 'Alpha', size: 100 },
      { name: 'EWBILLNO', description: 'EWAYBILLNO', type: 'Alpha', size: 50 },
      { name: 'InvTraNo', description: 'Inventory tra No', type: 'Alpha', size: 50 },
      { name: 'InvTraCNo', description: 'Inv. transfer. cancel no', type: 'Alpha', size: 50 },
      // Dedicated fields for the web app's own linked-document tracking (separate
      // from the legacy InvTraNo/InvTraCNo pair above, which turned out to be
      // stuck at a 1-character size in this company's DB and can't reliably be
      // resized via Service Layer metadata calls).
      { name: 'WebInvTraDocEntry', description: 'Web Inv. Transfer DocEntry', type: 'Numeric' },
      { name: 'WebInvTraDocNum', description: 'Web Inv. Transfer DocNum', type: 'Numeric' },
      { name: 'WebGoodsIssDocEntry', description: 'Web Goods Issue DocEntry', type: 'Numeric' },
      { name: 'WebGoodsIssDocNum', description: 'Web Goods Issue DocNum', type: 'Numeric' },
      { name: 'Series', description: 'Series', type: 'Alpha', size: 50 },
      { name: 'TranName', description: 'Transporter Name', type: 'Alpha', size: 100 },
      { name: 'ChallanNo', description: 'Challan No', type: 'Alpha', size: 50 },
      { name: 'ChallanDt', description: 'Challan Date', type: 'Date' },
      { name: 'NatureP', description: 'Nature Of Prcess', type: 'Alpha', size: 50 },
      { name: 'Canclled', description: 'Cancelled', type: 'Alpha', size: 50 },
      { name: 'ABILTO', description: 'Bill To', type: 'Alpha', size: 50 },
      { name: 'AADDID', description: 'Address ID', type: 'Alpha', size: 50 },
      { name: 'APOBOX', description: 'Street / PO Box', type: 'Alpha', size: 100 },
      { name: 'ASTRTNO', description: 'Street No', type: 'Alpha', size: 100 },
      { name: 'ABLDNO', description: 'Building/Floor/Room', type: 'Memo', size: 20 },
      { name: 'ABLOCK', description: 'Block', type: 'Alpha', size: 100 },
      { name: 'ACITY', description: 'City', type: 'Alpha', size: 100 },
      { name: 'AZIPCOD', description: 'Zip Code', type: 'Alpha', size: 50 },
      { name: 'ACOUNTY', description: 'County', type: 'Alpha', size: 50 },
      { name: 'ACNTRY', description: 'Country', type: 'Alpha', size: 50 },
      { name: 'ASTATE', description: 'State', type: 'Alpha', size: 50 },
      { name: 'AGSTIN', description: 'GSTIN', type: 'Alpha', size: 50 },
      { name: 'AGSTTYP', description: 'GST Type', type: 'Alpha', size: 50 },
      { name: 'ASHPFRM', description: 'Ship From', type: 'Alpha', size: 50 },
      { name: 'SADDID', description: 'Address ID', type: 'Alpha', size: 50 },
      { name: 'SPOBOX', description: 'Street / PO Box', type: 'Alpha', size: 100 },
      { name: 'SSTRTNO', description: 'Street No', type: 'Alpha', size: 100 },
      { name: 'SBLDNO', description: 'Building/Floor/Room', type: 'Memo', size: 20 },
      { name: 'SBLOCK', description: 'Block', type: 'Alpha', size: 100 },
      { name: 'SCITY', description: 'City', type: 'Alpha', size: 100 },
      { name: 'SZIPCOD', description: 'Zip Code', type: 'Alpha', size: 50 },
      { name: 'SCOUNTY', description: 'County', type: 'Alpha', size: 50 },
      { name: 'SCNTRY', description: 'Country', type: 'Alpha', size: 50 },
      { name: 'SSTATE', description: 'State', type: 'Alpha', size: 50 },
      { name: 'SGSTIN', description: 'GSTIN', type: 'Alpha', size: 50 },
      { name: 'SGSTTYP', description: 'GST Type', type: 'Alpha', size: 50 },
      { name: 'AFLOCC', description: 'From Location Country', type: 'Alpha', size: 50 },
      { name: 'AFLOCS', description: 'From Location State', type: 'Alpha', size: 50 },
      { name: 'ATOLOCC', description: 'To Location Country', type: 'Alpha', size: 50 },
      { name: 'ATOLOCS', description: 'To Location State', type: 'Alpha', size: 50 },
      { name: 'REMARKS', description: 'Remarks', type: 'Memo', size: 20 },
    ],
    childFields: {
      STTL_JWP1: [
        { name: 'ATARPTH', description: 'Target Path', type: 'Memo', size: 20 },
        { name: 'AFILE', description: 'File Name', type: 'Alpha', size: 200 },
        { name: 'ATTCHDT', description: 'Attachment Date', type: 'Date' },
        { name: 'AFRETXT', description: 'Free Text', type: 'Alpha', size: 100 },
      ],
      STTL_JWP2: [
        { name: 'RPONO', description: 'PO No', type: 'Alpha', size: 50 },
        { name: 'RPODATE', description: 'PO Date', type: 'Date' },
        { name: 'RGLACC', description: 'GL Account', type: 'Alpha', size: 50 },
        { name: 'RDES', description: 'Description', type: 'Alpha', size: 50 },
        { name: 'RORDQTY', description: 'Order Qty', type: 'Float' },
        { name: 'RUNITP', description: 'Unit Price', type: 'Float' },
        { name: 'RTOTAL', description: 'Total (LC)', type: 'Float' },
      ],
      STTL_JWP3: [
        { name: 'RINVNO', description: 'Inv No', type: 'Alpha', size: 50 },
        { name: 'RINVD', description: 'Inv Date', type: 'Date' },
        { name: 'RIGACC', description: 'GL Account', type: 'Alpha', size: 50 },
        { name: 'RIDES', description: 'Description', type: 'Alpha', size: 50 },
        { name: 'RIOQTY', description: 'Order Qty', type: 'Float' },
        { name: 'RIUNTP', description: 'Unit Price', type: 'Float' },
        { name: 'RITOTAL', description: 'Total (LC)', type: 'Float' },
      ],
      STTL_JWP4: [
        { name: 'RIPNO', description: 'IP No', type: 'Alpha', size: 50 },
        { name: 'RIPDATE', description: 'IP Date', type: 'Date' },
        { name: 'RITMNO', description: 'Item No', type: 'Alpha', size: 50 },
        { name: 'RITDES', description: 'Description', type: 'Alpha', size: 50 },
        { name: 'RITQTY', description: 'Quantity', type: 'Float' },
        { name: 'RITWHS', description: 'Whs', type: 'Alpha', size: 50 },
        { name: 'RITUOM', description: 'UoM', type: 'Alpha', size: 50 },
      ],
      STTL_JWP5: [
        { name: 'RPNO', description: 'RP No', type: 'Alpha', size: 50 },
        { name: 'RPDATE', description: 'RP Date', type: 'Date' },
        { name: 'RRITMNO', description: 'Item No', type: 'Alpha', size: 50 },
        { name: 'RRDES', description: 'Description', type: 'Alpha', size: 50 },
        { name: 'RRQTY', description: 'Quantity', type: 'Float' },
        { name: 'RRWHS', description: 'Whs', type: 'Alpha', size: 50 },
        { name: 'RRUOM', description: 'UoM', type: 'Alpha', size: 50 },
      ],
      STTL_JWP6: [
        { name: 'Series', description: 'Series', type: 'Alpha', size: 50 },
        { name: 'MITMNO', description: 'Item No', type: 'Alpha', size: 50 },
        { name: 'MDES', description: 'Description', type: 'Alpha', size: 150 },
        { name: 'MQTY', description: 'Quantity', type: 'Float' },
        { name: 'MWHS', description: 'Whs', type: 'Alpha', size: 50 },
        { name: 'TWHS', description: 'TWhs', type: 'Alpha', size: 50 },
        { name: 'MUOM', description: 'UoM', type: 'Alpha', size: 50 },
        { name: 'MBatch', description: 'Batch', type: 'Alpha', size: 50 },
        { name: 'MBinCode', description: 'BinCode', type: 'Alpha', size: 50 },
        { name: 'ToBinCode', description: 'ToBinCode', type: 'Alpha', size: 50 },
        { name: 'MDIFPNO', description: 'INV Tra No', type: 'Alpha', size: 50 },
        { name: 'OPCD', description: 'Operation Code', type: 'Alpha', size: 50 },
        { name: 'QTYINSTCK', description: 'Quantity in stock', type: 'Alpha', size: 50 },
        { name: 'QTYINWHS', description: 'Quantity in Whse', type: 'Alpha', size: 50 },
        { name: 'Rate', description: 'Rate', type: 'Float' },
        { name: 'PCS', description: 'PCS', type: 'Float' },
        { name: 'GRWIGHT', description: 'GRWEIGHT', type: 'Float' },
        { name: 'TRWIGHT', description: 'TRWEIGHT', type: 'Float' },
        { name: 'PBOBIN', description: 'PIPE BOBIN', type: 'Alpha', size: 50 },
        { name: 'TaxCD', description: 'TaxCode', type: 'Alpha', size: 50 },
        { name: 'Remarks', description: 'Remarks', type: 'Alpha', size: 200 },
        { name: 'Err', description: 'Error', type: 'Alpha', size: 250 },
        { name: 'Chk', description: 'Is Selected', type: 'Alpha', size: 20 },
      ],
      STTL_JWP7: [
        { name: 'Series', description: 'Series', type: 'Alpha', size: 50 },
        { name: 'MSACCOD', description: 'SAC Code', type: 'Alpha', size: 50 },
        { name: 'MGLACC', description: 'GL Account', type: 'Alpha', size: 50 },
        { name: 'MNOP', description: 'Nature of Process', type: 'Alpha', size: 50 },
        { name: 'MTAXCOD', description: 'Tax Code', type: 'Alpha', size: 50 },
        { name: 'MORDQTY', description: 'Order Qty', type: 'Float' },
        { name: 'MUNITP', description: 'Unit Price', type: 'Float' },
        { name: 'MTOTAL', description: 'Total (LC)', type: 'Float' },
        { name: 'MDBatch', description: 'Batch', type: 'Alpha', size: 50 },
        { name: 'MDBinCode', description: 'BinCode', type: 'Alpha', size: 50 },
        { name: 'MDPOD', description: 'PO Details', type: 'Alpha', size: 50 },
        { name: 'Err', description: 'Error', type: 'Alpha', size: 250 },
        { name: 'LOC', description: 'Location', type: 'Alpha', size: 100 },
      ],
      STTL_JWP8: [
        { name: 'Series', description: 'Series', type: 'Alpha', size: 50 },
        { name: 'MRITMNO', description: 'Item No', type: 'Alpha', size: 50 },
        { name: 'MRDES', description: 'Description', type: 'Alpha', size: 150 },
        { name: 'MRQTY', description: 'Quantity', type: 'Float' },
        { name: 'Price', description: 'Price', type: 'Float' },
        { name: 'MRWHS', description: 'Whs', type: 'Alpha', size: 50 },
        { name: 'MRUOM', description: 'UoM', type: 'Alpha', size: 50 },
        { name: 'MRBatch', description: 'Batch', type: 'Alpha', size: 50 },
        { name: 'MRBinCode', description: 'BinCode', type: 'Alpha', size: 50 },
        { name: 'MRGINO', description: 'Goods Issue No', type: 'Alpha', size: 50 },
        { name: 'Err', description: 'Error', type: 'Alpha', size: 250 },
        { name: 'RFPType', description: 'RFPType', type: 'Alpha', size: 50, validValues: 'RFPType' },
      ],
      STTL_JWP9: [
        { name: 'Series', description: 'Series', type: 'Alpha', size: 50 },
        { name: 'MRITMNO', description: 'Item No', type: 'Alpha', size: 50 },
        { name: 'MRDES', description: 'Description', type: 'Alpha', size: 150 },
        { name: 'MRQTY', description: 'Quantity', type: 'Float' },
        { name: 'Price', description: 'Price', type: 'Float' },
        { name: 'MRWHS', description: 'Whs', type: 'Alpha', size: 50 },
        { name: 'MRUOM', description: 'UoM', type: 'Alpha', size: 50 },
        { name: 'MRBatch', description: 'Batch', type: 'Alpha', size: 50 },
        { name: 'MRBinCode', description: 'BinCode', type: 'Alpha', size: 50 },
        { name: 'MRGRNO', description: 'Goods Receipt No', type: 'Alpha', size: 50 },
        { name: 'Err', description: 'Error', type: 'Alpha', size: 250 },
        { name: 'RFPType', description: 'RFPType', type: 'Alpha', size: 50, validValues: 'RFPType' },
      ],
    },
    udo: {
      objectType: 'STTL_JWPM',
      name: 'JobWork Purchase Process',
      manageSeries: true,
      childTables: ['STTL_JWP1', 'STTL_JWP2', 'STTL_JWP3', 'STTL_JWP4', 'STTL_JWP5', 'STTL_JWP6', 'STTL_JWP7', 'STTL_JWP8', 'STTL_JWP9'],
      findColumns: ['JWOSER', 'JWONUO', 'JWOSTS', 'BRNCH', 'PDATE', 'DDATE', 'DOCDATE', 'OWOR', 'VENCOD', 'VENNAME', 'JWOPAYT', 'SLSEMP'],
    },
  },

  jobworkReceiptReturnNote: {
    menuName: 'Jobwork Receipt / Return Note',
    menuPath: '/jobwork-receipt-note',
    group: 'Purchase J/W',
    partyType: 'vendor',
    listFields: { statusField: 'JWOSTS', partyCodeField: 'VENCOD', partyNameField: 'VENNAME', postingDateField: 'PDATE', docDateField: 'DOCDATE', primaryLineTable: 'STTL_JWPR6' },
    masterTable: { name: 'STTL_JWPMR', description: 'JobWork Purchase Return Master' },
    childTables: [
      { name: 'STTL_JWPR1', description: 'JobWork PR Attachment Detail', role: 'attachments' },
      { name: 'STTL_JWPR6', description: 'JobWork PR DELIFP Detail', role: 'lines' },
      { name: 'STTL_JWPR8', description: 'JobWork PR Goods Issue Detail', role: 'goodsIssue' },
      { name: 'STTL_JWPR9', description: 'JobWork PR GoodsReceipt Detail', role: 'goodsReceipt' },
    ],
    masterFields: [
      { name: 'JWOSER', description: 'Jobwork Order Series', type: 'Alpha', size: 50 },
      { name: 'JWONUO', description: 'Jobwork Order No', type: 'Alpha', size: 50 },
      { name: 'JWOSTS', description: 'Jobwork Order Status', type: 'Alpha', size: 50 },
      { name: 'BRNCH', description: 'Branch', type: 'Alpha', size: 50 },
      { name: 'PDATE', description: 'Posting Date', type: 'Date' },
      { name: 'DDATE', description: 'Delivery Date', type: 'Date' },
      { name: 'DOCDATE', description: 'Document Date', type: 'Date' },
      { name: 'OWOR', description: 'Own Work Order Ref', type: 'Alpha', size: 50 },
      { name: 'VENCOD', description: 'Vendor Code', type: 'Alpha', size: 50 },
      { name: 'VENNAME', description: 'Vendor Name', type: 'Alpha', size: 100 },
      { name: 'JWOPAYT', description: 'Payment Term', type: 'Alpha', size: 50 },
      { name: 'SLSEMP', description: 'Sales Employee', type: 'Alpha', size: 50 },
      { name: 'VEHNO', description: 'Vehicle Number', type: 'Alpha', size: 50 },
      { name: 'KNTWEIGHT', description: 'Kata Weight', type: 'Alpha', size: 100 },
      { name: 'EWBILLNO', description: 'EWAYBILLNO', type: 'Alpha', size: 50 },
      { name: 'PONo', description: 'JW Ref No', type: 'Alpha', size: 50 },
      { name: 'JWTYP', description: 'JW Type', type: 'Alpha', size: 50 },
      { name: 'InvTra', description: 'Inventory transfer Req.', type: 'Alpha', size: 50 },
      { name: 'CInvTra', description: 'Cancle Inv. Tra. req.', type: 'Alpha', size: 50 },
      { name: 'GoodsIssueN', description: 'Goods Iss No', type: 'Alpha', size: 50 },
      { name: 'CGoodsIssueN', description: 'Cancle goods Iss', type: 'Alpha', size: 100 },
      { name: 'GoodsReceiptNo', description: 'Goods Rec No', type: 'Alpha', size: 50 },
      { name: 'CGoodsReceiptNo', description: 'Cancle Goods Rec No', type: 'Alpha', size: 50 },
      { name: 'ISeries', description: 'Inv. Tra. Series', type: 'Alpha', size: 100 },
      { name: 'GRSeries', description: 'Goods Rec. Series', type: 'Alpha', size: 50 },
      { name: 'GISeries', description: 'Goods Iss. Series', type: 'Alpha', size: 50 },
      { name: 'TranName', description: 'Transporter Name', type: 'Alpha', size: 100 },
      { name: 'ChallanNo', description: 'Challan No', type: 'Alpha', size: 50 },
      { name: 'ChallanDt', description: 'Challan Date', type: 'Date' },
      { name: 'NatureP', description: 'Nature Of Prcess', type: 'Alpha', size: 50 },
      { name: 'Cancel', description: 'Cancel Document', type: 'Alpha', size: 1 },
      { name: 'ABILTO', description: 'Bill To', type: 'Alpha', size: 50 },
      { name: 'AADDID', description: 'Address ID', type: 'Alpha', size: 50 },
      { name: 'APOBOX', description: 'Street / PO Box', type: 'Alpha', size: 100 },
      { name: 'ASTRTNO', description: 'Street No', type: 'Alpha', size: 100 },
      { name: 'ABLDNO', description: 'Building/Floor/Room', type: 'Memo', size: 20 },
      { name: 'ABLOCK', description: 'Block', type: 'Alpha', size: 100 },
      { name: 'ACITY', description: 'City', type: 'Alpha', size: 100 },
      { name: 'AZIPCOD', description: 'Zip Code', type: 'Alpha', size: 50 },
      { name: 'ACOUNTY', description: 'County', type: 'Alpha', size: 50 },
      { name: 'ACNTRY', description: 'Country', type: 'Alpha', size: 50 },
      { name: 'ASTATE', description: 'State', type: 'Alpha', size: 50 },
      { name: 'AGSTIN', description: 'GSTIN', type: 'Alpha', size: 50 },
      { name: 'AGSTTYP', description: 'GST Type', type: 'Alpha', size: 50 },
      { name: 'ASHPFRM', description: 'Ship From', type: 'Alpha', size: 50 },
      { name: 'SADDID', description: 'Address ID', type: 'Alpha', size: 50 },
      { name: 'SPOBOX', description: 'Street / PO Box', type: 'Alpha', size: 100 },
      { name: 'SSTRTNO', description: 'Street No', type: 'Alpha', size: 100 },
      { name: 'SBLDNO', description: 'Building/Floor/Room', type: 'Memo', size: 20 },
      { name: 'SBLOCK', description: 'Block', type: 'Alpha', size: 100 },
      { name: 'SCITY', description: 'City', type: 'Alpha', size: 100 },
      { name: 'SZIPCOD', description: 'Zip Code', type: 'Alpha', size: 50 },
      { name: 'SCOUNTY', description: 'County', type: 'Alpha', size: 50 },
      { name: 'SCNTRY', description: 'Country', type: 'Alpha', size: 50 },
      { name: 'SSTATE', description: 'State', type: 'Alpha', size: 50 },
      { name: 'SGSTIN', description: 'GSTIN', type: 'Alpha', size: 50 },
      { name: 'SGSTTYP', description: 'GST Type', type: 'Alpha', size: 50 },
      { name: 'AFLOCC', description: 'From Location Country', type: 'Alpha', size: 50 },
      { name: 'AFLOCS', description: 'From Location State', type: 'Alpha', size: 50 },
      { name: 'ATOLOCC', description: 'To Location Country', type: 'Alpha', size: 50 },
      { name: 'ATOLOCS', description: 'To Location State', type: 'Alpha', size: 50 },
      { name: 'VPONo', description: 'Vendor PO No', type: 'Alpha', size: 50 },
      { name: 'VPODT', description: 'Vendor PO Date', type: 'Date' },
      { name: 'REMARKS', description: 'Remarks', type: 'Memo', size: 20 },
      // Real SAP links for the stock movements this document posts — mirrors
      // the WebGoodsRcptDocEntry pattern already used elsewhere, replacing the
      // legacy GoodsIssueN/GoodsReceiptNo/InvTra free-text fields above (which
      // the old add-on filled in manually rather than linking). Per the legacy
      // VB.NET screen (JW_Pur_R.b1f.cs): JWTYP=='R' posts a Goods Issue (RM
      // consumption, from STTL_JWPR8) + a Goods Receipt (finished goods, from
      // STTL_JWPR9) together; JWTYP=='RE' posts only a Stock Transfer (return,
      // from STTL_JWPR6) reversing material back to the source warehouse.
      { name: 'WebGoodsIssDocEntry', description: 'Web Goods Issue DocEntry', type: 'Numeric' },
      { name: 'WebGoodsIssDocNum', description: 'Web Goods Issue DocNum', type: 'Numeric' },
      { name: 'WebGoodsRcptDocEntry', description: 'Web Goods Receipt DocEntry', type: 'Numeric' },
      { name: 'WebGoodsRcptDocNum', description: 'Web Goods Receipt DocNum', type: 'Numeric' },
      { name: 'WebInvTraRtnDocEntry', description: 'Web Inv. Transfer Return DocEntry', type: 'Numeric' },
      { name: 'WebInvTraRtnDocNum', description: 'Web Inv. Transfer Return DocNum', type: 'Numeric' },
    ],
    childFields: {
      STTL_JWPR1: [
        { name: 'ATARPTH', description: 'Target Path', type: 'Memo', size: 20 },
        { name: 'AFILE', description: 'File Name', type: 'Alpha', size: 200 },
        { name: 'ATTCHDT', description: 'Attachment Date', type: 'Date' },
        { name: 'AFRETXT', description: 'Free Text', type: 'Alpha', size: 100 },
      ],
      STTL_JWPR6: [
        { name: 'Series', description: 'Series', type: 'Alpha', size: 50 },
        { name: 'MITMNO', description: 'Item No', type: 'Alpha', size: 50 },
        { name: 'MDES', description: 'Description', type: 'Alpha', size: 150 },
        { name: 'MQTY', description: 'Quantity', type: 'Float' },
        { name: 'MWHS', description: 'Whs', type: 'Alpha', size: 50 },
        { name: 'TWHS', description: 'TWhs', type: 'Alpha', size: 50 },
        { name: 'MUOM', description: 'UoM', type: 'Alpha', size: 50 },
        { name: 'MBatch', description: 'Batch', type: 'Alpha', size: 50 },
        { name: 'MBinCode', description: 'BinCode', type: 'Alpha', size: 50 },
        { name: 'ToBinCode', description: 'ToBinCode', type: 'Alpha', size: 50 },
        { name: 'MDIFPNO', description: 'INV Tra No', type: 'Alpha', size: 50 },
        { name: 'TaxCD', description: 'TaxCode', type: 'Alpha', size: 50 },
        { name: 'Remarks', description: 'Remarks', type: 'Alpha', size: 200 },
        { name: 'PJWNO', description: 'Purcase JW No', type: 'Alpha', size: 50 },
        { name: 'PJWDEN', description: 'Pur JW DocEnt', type: 'Alpha', size: 50 },
        { name: 'RETQTY', description: 'Return Quantiy', type: 'Float' },
        { name: 'TOTQTY', description: 'Total Quantiy', type: 'Float' },
        { name: 'Err', description: 'Error', type: 'Alpha', size: 250 },
        { name: 'Chk', description: 'Is Selected', type: 'Alpha', size: 20 },
        { name: 'OPCode', description: 'Opration Code', type: 'Alpha', size: 100 },
        { name: 'INStockQty', description: 'In Stock Qty', type: 'Float' },
        { name: 'QTYInWhs', description: 'Qty in whse', type: 'Float' },
        { name: 'Rate', description: 'Rate', type: 'Float' },
        { name: 'PcsMtr', description: 'Pcs / Mtr', type: 'Float' },
        { name: 'GWeight', description: 'Gross Weight', type: 'Float' },
        { name: 'TWeight', description: 'Tare Weight', type: 'Float' },
        { name: 'PBobin', description: 'Pipe Bobin', type: 'Alpha', size: 100 },
        { name: 'TaxCode', description: 'TaxCode', type: 'Alpha', size: 100 },
      ],
      STTL_JWPR8: [
        { name: 'Series', description: 'Series', type: 'Alpha', size: 50 },
        { name: 'MRITMNO', description: 'Item No', type: 'Alpha', size: 50 },
        { name: 'MRDES', description: 'Description', type: 'Alpha', size: 150 },
        { name: 'MRQTY', description: 'Quantity', type: 'Float' },
        { name: 'Price', description: 'Price', type: 'Float' },
        { name: 'MRWHS', description: 'Whs', type: 'Alpha', size: 50 },
        { name: 'MRUOM', description: 'UoM', type: 'Alpha', size: 50 },
        { name: 'MRBatch', description: 'Batch', type: 'Alpha', size: 50 },
        { name: 'MRBinCode', description: 'BinCode', type: 'Alpha', size: 50 },
        { name: 'MRGINO', description: 'Goods Issue No', type: 'Alpha', size: 50 },
        { name: 'Err', description: 'Error', type: 'Alpha', size: 250 },
        { name: 'RFPType', description: 'RFPType', type: 'Alpha', size: 50, validValues: 'RFPType' },
        { name: 'JWNO', description: 'Job Work No', type: 'Alpha', size: 50 },
        { name: 'PJWNO', description: 'Purcase JW No', type: 'Alpha', size: 50 },
        { name: 'PJWDEN', description: 'Pur JW DocEnt', type: 'Alpha', size: 50 },
        { name: 'BalQTY', description: 'Balance Quantiy', type: 'Float' },
        { name: 'FinalQty', description: 'Final Quantiy', type: 'Float' },
        { name: 'OPCode', description: 'Opration Code', type: 'Alpha', size: 100 },
        { name: 'INSQty', description: 'In Stock Qty', type: 'Float' },
        { name: 'QTYInWhs', description: 'Quantity in whse', type: 'Float' },
        { name: 'Rate', description: 'Rate', type: 'Float' },
        { name: 'PcsMtr', description: 'Pcs / Mtr', type: 'Float' },
        { name: 'TaxCode', description: 'TaxCode', type: 'Alpha', size: 100 },
      ],
      STTL_JWPR9: [
        { name: 'Series', description: 'Series', type: 'Alpha', size: 50 },
        { name: 'MRITMNO', description: 'Item No', type: 'Alpha', size: 50 },
        { name: 'MRDES', description: 'Description', type: 'Alpha', size: 150 },
        { name: 'MRQTY', description: 'Quantity', type: 'Float' },
        { name: 'Price', description: 'Price', type: 'Float' },
        { name: 'MRWHS', description: 'Whs', type: 'Alpha', size: 50 },
        { name: 'MRUOM', description: 'UoM', type: 'Alpha', size: 50 },
        { name: 'MRBatch', description: 'Batch', type: 'Alpha', size: 50 },
        { name: 'MRBinCode', description: 'BinCode', type: 'Alpha', size: 50 },
        { name: 'MRGRNO', description: 'Goods Receipt No', type: 'Alpha', size: 50 },
        { name: 'Err', description: 'Error', type: 'Alpha', size: 250 },
        { name: 'RFPType', description: 'RFPType', type: 'Alpha', size: 50, validValues: 'RFPType' },
        { name: 'PCS', description: 'PCS', type: 'Float' },
        { name: 'GWeight', description: 'Gross Weight', type: 'Float' },
        { name: 'TWeight', description: 'Tare Weight', type: 'Float' },
        { name: 'Remarks', description: 'Remarks', type: 'Alpha', size: 200 },
        { name: 'PBOBIN', description: 'PBOBIN', type: 'Alpha', size: 200 },
      ],
    },
    udo: {
      objectType: 'STTL_JWPMR',
      name: 'JobWork Purchase R Process',
      manageSeries: true,
      childTables: ['STTL_JWPR1', 'STTL_JWPR6', 'STTL_JWPR8', 'STTL_JWPR9'],
      findColumns: ['JWOSER', 'JWONUO', 'JWOSTS', 'BRNCH', 'PDATE', 'DDATE', 'DOCDATE', 'OWOR', 'VENCOD', 'VENNAME'],
    },
  },
};

/**
 * Internal batch-selection helper UDOs used by the legacy add-on's popup dialogs
 * (BatchIssue.b1f / BatchReceipt.b1f). Provisioned for schema parity but not
 * surfaced as standalone sidebar menu items or pages in this pass.
 */
const BATCH_HELPER_UDOS = {
  jobworkBatchReceiptMaster: {
    masterTable: { name: 'STTL_JWBRM', description: 'Jobwork Batch Rec Master' },
    childTables: [{ name: 'STTL_JWBR1', description: 'Jobwork Batch Rec Detail' }],
    masterFields: [
      { name: 'JWNo', description: 'Jobwork Order No', type: 'Alpha', size: 50 },
      { name: 'JWSer', description: 'Jobwork Order Series', type: 'Alpha', size: 50 },
      { name: 'BaseType', description: 'BaseType', type: 'Alpha', size: 50 },
      { name: 'ICode', description: 'ItemCode', type: 'Alpha', size: 50 },
      { name: 'WhsCode', description: 'WhsCode', type: 'Alpha', size: 50 },
      { name: 'BinCode', description: 'BinCode', type: 'Alpha', size: 50 },
      { name: 'Qty', description: 'Quantity', type: 'Float' },
      { name: 'LineId', description: 'LineId', type: 'Alpha', size: 50 },
    ],
    childFields: {
      STTL_JWBR1: [
        { name: 'BatchNo', description: 'Batch No', type: 'Alpha', size: 50 },
        { name: 'Qty', description: 'Batch Qty', type: 'Float' },
        { name: 'Att1', description: 'Att1', type: 'Alpha', size: 50 },
        { name: 'Att2', description: 'Att2', type: 'Alpha', size: 50 },
        { name: 'Status', description: 'Status', type: 'Alpha', size: 50 },
        { name: 'ExDate', description: 'Expire Date', type: 'Date' },
        { name: 'MfrDate', description: 'Mfr Date', type: 'Date' },
        { name: 'AdmDate', description: 'Admission Date', type: 'Date' },
        { name: 'Location', description: 'Location', type: 'Alpha', size: 50 },
        { name: 'Details', description: 'Details', type: 'Memo', size: 10 },
      ],
    },
    udo: {
      objectType: 'STTL_JWBRM',
      name: 'Jobwork Batch Rec Master',
      manageSeries: false,
      childTables: ['STTL_JWBR1'],
      findColumns: ['JWNo', 'JWSer', 'BaseType'],
    },
  },
  jobworkBatchIssueMaster: {
    masterTable: { name: 'STTL_JWBIM', description: 'Jobwork Batch Issue Master' },
    childTables: [{ name: 'STTL_JWBI1', description: 'Jobwork Batch Issue Detail' }],
    masterFields: [
      { name: 'JWNo', description: 'Jobwork Order No', type: 'Alpha', size: 50 },
      { name: 'JWSer', description: 'Jobwork Order Series', type: 'Alpha', size: 50 },
      { name: 'BaseType', description: 'BaseType', type: 'Alpha', size: 50 },
      { name: 'BaseLine', description: 'BaseLine', type: 'Alpha', size: 50 },
      { name: 'ICode', description: 'ItemCode', type: 'Alpha', size: 50 },
      { name: 'WhsCode', description: 'WhsCode', type: 'Alpha', size: 50 },
      { name: 'BinCode', description: 'BinCode', type: 'Alpha', size: 50 },
      { name: 'Qty', description: 'Quantity', type: 'Float' },
    ],
    childFields: {
      STTL_JWBI1: [
        { name: 'Chk', description: 'Is Selected', type: 'Alpha', size: 1 },
        { name: 'BatchNo', description: 'Batch No', type: 'Alpha', size: 50 },
        { name: 'Qty', description: 'Batch Qty', type: 'Float' },
        { name: 'SQty', description: 'Selected Qty', type: 'Float' },
        { name: 'AvailQTY', description: 'Avail Qty', type: 'Float' },
      ],
    },
    udo: {
      objectType: 'STTL_JWBIM',
      name: 'Jobwork Batch Issue Master',
      manageSeries: false,
      childTables: ['STTL_JWBI1'],
      findColumns: ['JWNo', 'JWSer', 'BaseType'],
    },
  },
};

/** UDFs added directly onto standard SAP tables (not UDTs) for cross-document traceability. */
const STANDARD_TABLE_UDFS = [
  { table: 'ODLN', name: 'DocType', description: 'Document Type', type: 'Alpha', size: 100 },
  { table: 'ODLN', name: 'JWNo', description: 'Jobwork No', type: 'Alpha', size: 20 },
  { table: 'OWOR', name: 'JWNo', description: 'Jobwork No', type: 'Alpha', size: 20 },
  { table: 'ODLN', name: 'JWRNo', description: 'Jobwork Return No', type: 'Alpha', size: 20 },
  { table: 'DLN1', name: 'Rejres', description: 'Rejection Reason', type: 'Alpha', size: 100 },
  { table: 'OWOR', name: 'JWRNo', description: 'Jobwork Return No', type: 'Alpha', size: 20 },
  // Reverse link on the real stock documents the web app's Jobwork Issue Note
  // generates, back to the Jobwork Issue Note that created them — the SAP-side
  // half of the golden-arrow pair (see jobWorkIssueNotePostingService.js).
  { table: 'OWTR', name: 'JobWorkDocEntry', description: 'Jobwork Issue Note DocEntry', type: 'Numeric' },
  { table: 'OWTR', name: 'JobWorkDocNum', description: 'Jobwork Issue Note DocNum', type: 'Numeric' },
  { table: 'OIGE', name: 'JobWorkDocEntry', description: 'Jobwork Issue Note DocEntry', type: 'Numeric' },
  { table: 'OIGE', name: 'JobWorkDocNum', description: 'Jobwork Issue Note DocNum', type: 'Numeric' },
  // Same golden-arrow convention for the Customer Receipt Note's real Inventory
  // Goods Receipt (OIGN) — a distinct field pair since it's a different SAP
  // table from OWTR/OIGE above, so no collision with the purchase-side link.
  { table: 'OIGN', name: 'CustReceiptDocEntry', description: 'Customer Receipt Note DocEntry', type: 'Numeric' },
  { table: 'OIGN', name: 'CustReceiptDocNum', description: 'Customer Receipt Note DocNum', type: 'Numeric' },
  // Same golden-arrow convention for the Customer Issue / Return Note's real
  // Inventory Goods Issue (OIGE) — a distinct field pair from Jobwork Issue
  // Note's JobWorkDocEntry/JobWorkDocNum above, since both transaction types
  // can post to this same OIGE table and must not collide.
  { table: 'OIGE', name: 'CustIssueDocEntry', description: 'Customer Issue / Return Note DocEntry', type: 'Numeric' },
  { table: 'OIGE', name: 'CustIssueDocNum', description: 'Customer Issue / Return Note DocNum', type: 'Numeric' },
  // Jobwork Receipt/Return Note (Purchase J/W) — yet another distinct field
  // set on the same shared real SAP tables (OIGE/OIGN/OWTR), since Jobwork
  // Issue Note, Customer Issue/Return Note, and this transaction can all post
  // to them independently and must never be confused for one another.
  { table: 'OIGE', name: 'JWPurRcptGIDocEntry', description: 'Jobwork Receipt Note Goods Issue DocEntry', type: 'Numeric' },
  { table: 'OIGE', name: 'JWPurRcptGIDocNum', description: 'Jobwork Receipt Note Goods Issue DocNum', type: 'Numeric' },
  { table: 'OIGN', name: 'JWPurRcptGRDocEntry', description: 'Jobwork Receipt Note Goods Receipt DocEntry', type: 'Numeric' },
  { table: 'OIGN', name: 'JWPurRcptGRDocNum', description: 'Jobwork Receipt Note Goods Receipt DocNum', type: 'Numeric' },
  { table: 'OWTR', name: 'JWPurRcptRtnDocEntry', description: 'Jobwork Receipt Note Return Transfer DocEntry', type: 'Numeric' },
  { table: 'OWTR', name: 'JWPurRcptRtnDocNum', description: 'Jobwork Receipt Note Return Transfer DocNum', type: 'Numeric' },
];

const getTransaction = (transactionKey) => {
  const transaction = TRANSACTIONS[transactionKey];
  if (!transaction) {
    const error = new Error(`Unknown Job Work transaction: ${transactionKey}`);
    error.statusCode = 404;
    throw error;
  }
  return transaction;
};

module.exports = {
  VALID_VALUES,
  TRANSACTIONS,
  BATCH_HELPER_UDOS,
  STANDARD_TABLE_UDFS,
  getTransaction,
};
